# Generated by Django 3.0.7 on 2020-06-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producent', models.TextField(blank=True)),
                ('wydawca', models.TextField(blank=True)),
                ('tytul', models.TextField(blank=True)),
                ('aktorzy', models.TextField(blank=True)),
                ('scenarzysta', models.TextField(blank=True)),
                ('kategoria', models.TextField(blank=True)),
                ('ocena', models.CharField(max_length=3)),
                ('status', models.TextField(blank=True)),
            ],
        ),
    ]
